version: '3.8'

services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: ecommerce-api
    container_name: api
    ports:
      - ${PORT}:8000
    depends_on:
      - db

  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
