version: '3.8'

services:

  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql-db
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306

volumes:
  database:
